/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personel;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class AbsentAdd extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    
    DefaultComboBoxModel combo_prenom_absent= new DefaultComboBoxModel();
    
    public AbsentAdd() {
        initComponents();
        String nom = null;
        
        try {
            stm = conn.obtenirconnexion().createStatement();
            ResultSet fr = stm.executeQuery("Select nom from perso order by nom");
            combo_prenom_absent.removeAllElements();
            while (fr.next()) {
                combo_prenom_absent.addElement(fr.getString("nom"));
                nom = fr.getString("nom");
            }jComboBox1.setModel(combo_prenom_absent);
            
            
        } catch (SQLException e) {
            System.err.println(e);
        }
        

        try {
            stm = conn.obtenirconnexion().createStatement();
            ResultSet fr = stm.executeQuery("Select matricul from perso where nom = '"+nom+"'");
            fr.next();
            jLabel16.setText(fr.getString("matricul"));
        } catch (SQLException e) {
            System.err.println(e);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        datedebut = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        datefin = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(323, 412));
        setMinimumSize(new java.awt.Dimension(323, 412));
        setPreferredSize(new java.awt.Dimension(323, 412));
        setResizable(false);
        getContentPane().setLayout(null);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(98, 51, 207, 29);

        jLabel13.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nom:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 51, 80, 28);

        jLabel16.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Immatriculation");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(98, 86, 207, 29);

        datedebut.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(datedebut);
        datedebut.setBounds(98, 128, 207, 26);

        jLabel21.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Début:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(10, 128, 80, 26);

        jLabel23.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Fin:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 172, 80, 26);

        datefin.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(datefin);
        datefin.setBounds(98, 172, 207, 26);

        jLabel18.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Motif:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 229, 78, 27);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(98, 229, 206, 83);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personel/valider.PNG"))); // NOI18N
        jButton3.setText("Valider");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(98, 330, 110, 40);

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(214, 330, 90, 40);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 330, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        try {
            stm = conn.obtenirconnexion().createStatement();
            ResultSet fr = stm.executeQuery("Select matricul from perso where nom = '"+jComboBox1.getSelectedItem().toString()+"'");
            fr.next();
            jLabel16.setText(fr.getString("matricul"));
        } catch (SQLException e) {
            System.err.println(e);
        }

        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (jComboBox1.getSelectedItem() == null || datedebut.getDate().toString().equals("") || datefin.getDate().toString().equals("") || jTextArea1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Completez tous les champs necessaires!");
        }else{

            jButton3.setEnabled(true);
            String matricul = jLabel16.getText();
            String nom = jComboBox1.getSelectedItem().toString();
            String datedb = String.format("%1$tY-%1$tm-%1$td",datedebut.getDate());
            String datefn = String.format("%1$tY-%1$tm-%1$td",datefin.getDate());

            String motif = jTextArea1.getText();

            String requete = "insert into absent(matricul,nom,datedebut,datefin,motif)VALUES('"
            + matricul + "','" + nom + "','" + datedb + "','" + datefn + "','" + motif + "')";
            try {
                stm.executeUpdate(requete);
                JOptionPane.showMessageDialog(null, "Effectué");
                this.dispose();

            } catch (HeadlessException | SQLException ex)   {
                JOptionPane.showMessageDialog(null, "erreur 1");
                JOptionPane.showMessageDialog(null, "erreur de suppression \n" + ex.getMessage());

            }

        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbsentAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser datedebut;
    private com.toedter.calendar.JDateChooser datefin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
