/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personel;

import java.awt.HeadlessException;
import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class AvanceAdd extends javax.swing.JFrame {
    
    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    
    DefaultComboBoxModel combo_nom= new DefaultComboBoxModel();
    
    
    public AvanceAdd() {
        initComponents();
        
        try {
            combo_nom.removeAllElements();
            stm = conn.obtenirconnexion().createStatement();
            ResultSet fr = stm.executeQuery("Select nom from perso order by nom");
            while (fr.next()) {
                combo_nom.addElement(fr.getString(1));
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        com_avance.setModel(combo_nom);
        
        try {

                String nom = com_avance.getSelectedItem().toString();
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select matricul,salaire_rest from perso where nom ='"+nom+"'");
                fr.next();
                txt_imm_avance.setText(fr.getString(1));
                txt_salaire.setText(fr.getString("salaire_rest")+" Ar");
            } catch (SQLException e) {
                System.err.println(e);
            }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_avance = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        com_avance = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        txt_salaire = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_imm_avance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(371, 302));
        setMinimumSize(new java.awt.Dimension(371, 302));
        setPreferredSize(new java.awt.Dimension(371, 302));
        getContentPane().setLayout(null);

        txt_avance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt_avance);
        txt_avance.setBounds(100, 170, 250, 32);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Avance (Ar):");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(10, 170, 87, 32);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personel/131 copie.png"))); // NOI18N
        jButton9.setText("Enregistrer");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        com_avance.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                com_avanceItemStateChanged(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Nom:");

        txt_salaire.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_salaire.setForeground(new java.awt.Color(255, 255, 255));
        txt_salaire.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_salaire.setText("Immatriculation");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Salaire restant:");

        txt_imm_avance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_imm_avance.setForeground(new java.awt.Color(255, 255, 255));
        txt_imm_avance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_imm_avance.setText("Immatriculation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_imm_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(com_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_salaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(txt_imm_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_salaire, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void com_avanceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_com_avanceItemStateChanged

        if (com_avance.getSelectedItem() == null){

        }else{
            try {

                String nom = com_avance.getSelectedItem().toString();
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select matricul,salaire_rest from perso where nom ='"+nom+"'");
                fr.next();
                txt_imm_avance.setText(fr.getString(1));
                txt_salaire.setText(fr.getString("salaire_rest")+" Ar");
            } catch (SQLException e) {
                System.err.println(e);
            }

        }
    }//GEN-LAST:event_com_avanceItemStateChanged

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (com_avance.getSelectedItem() == null){

        }else{

            String matricul = txt_imm_avance.getText();
            String nom = null;
            int salaire = 0;
            int salaire_rest;
            try {
                ResultSet fr = stm.executeQuery("Select nom,salaire from perso where matricul='"+matricul+"'");
                fr.next();
                nom = fr.getString(1);
                salaire = fr.getInt(2);

            } catch (SQLException e) {
                System.err.println(e);
            }
            int avance = parseInt(txt_avance.getText());
            salaire_rest = salaire - avance;

            String date = null;
            try {
                ResultSet fr = stm.executeQuery("Select now()");
                fr.next();
                date = fr.getString(1);
            } catch (SQLException e) {
                System.err.println(e);
            }

            String requete = "insert into avance(matricul,nom,avance,date)VALUES('"
            + matricul + "','" + nom + "','" + avance + "','" + date + "')";
            String requete2 = "update perso set salaire_rest ='"+salaire_rest+"' where matricul='"+matricul+"'";
            try {
                stm.executeUpdate(requete);
                stm.executeUpdate(requete2);
                
                this.dispose();
                JOptionPane.showMessageDialog(null, "Effectué");

            } catch (HeadlessException | SQLException ex)   {
                
                JOptionPane.showMessageDialog(null, "erreur\n" + ex.getMessage());

            }

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvanceAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvanceAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvanceAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvanceAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvanceAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox com_avance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_avance;
    private javax.swing.JLabel txt_imm_avance;
    private javax.swing.JLabel txt_salaire;
    // End of variables declaration//GEN-END:variables
}
