/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personel;

import java.awt.HeadlessException;
import static java.lang.Float.parseFloat;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class CongeModif extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    
    String id_conge = stockcarre.MenuPrincipal.pers.selected_id_conge;
    float old_conge = 0;
    
    public CongeModif() {
        initComponents();
        
        try{
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select * from conge where numero ='"+id_conge+"'");

                fr.next();
                        txt_nom.setText(fr.getString("nom"));
                        txt_im1.setText(fr.getString("matricul"));
                        txt_nbr_cong.setText(fr.getString("nbr_jr"));
                        old_conge = fr.getFloat("nbr_jr");
                        jDateChooser1.setDate(fr.getDate("datedebut"));
                        jDateChooser2.setDate(fr.getDate("datefin"));

            }catch (HeadlessException | SQLException ex) {
            }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txt_nbr_cong = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JLabel();
        txt_im1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(339, 400));
        setMinimumSize(new java.awt.Dimension(339, 400));
        setPreferredSize(new java.awt.Dimension(339, 400));
        getContentPane().setLayout(null);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personel/131 copie.png"))); // NOI18N
        jButton11.setText("Enregistrer");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(90, 310, 130, 35);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Fin:");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(10, 260, 71, 34);

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 310, 90, 35);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Nombre de jour:");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(10, 170, 129, 34);
        getContentPane().add(txt_nbr_cong);
        txt_nbr_cong.setBounds(150, 170, 169, 34);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Début:");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(10, 220, 71, 34);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(90, 220, 230, 34);

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(90, 260, 230, 34);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Prénom:");

        txt_nom.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_nom.setForeground(new java.awt.Color(0, 204, 204));
        txt_nom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nom.setText("jLabel1");

        txt_im1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_im1.setForeground(new java.awt.Color(0, 204, 204));
        txt_im1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_im1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(110, Short.MAX_VALUE)
                    .addComponent(txt_im1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(txt_im1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 340, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

            String matricul = txt_im1.getText();
            String nom = null;
            float cong = 0;
            float conge_rest;
            
            if(txt_nbr_cong.getText().equals("")){           
                old_conge = 0;
            }else{}
            
            
            
            try {
                ResultSet fr = stm.executeQuery("Select nom,conge from perso where matricul='"+matricul+"'");
                fr.next();
                nom = fr.getString(1);
                cong = fr.getFloat(2);

            } catch (SQLException e) {
                System.err.println(e);
            }

            float nbr_jour = parseFloat(txt_nbr_cong.getText());
            String datedb = String.format("%1$tY-%1$tm-%1$td",jDateChooser1.getDate());
            String datefn = String.format("%1$tY-%1$tm-%1$td",jDateChooser2.getDate());

            conge_rest = cong - nbr_jour;

            String requete = "update conge set nbr_jr = '"+nbr_jour+"', datedebut = '"+datedb+"',"
                    + "datefin = '"+datefn+"' where numero = '"+id_conge+"'";

            String requete2 = "update perso set conge_rest='"+conge_rest+"' where matricul ='"+matricul+"'";

            try {
                stm.executeUpdate(requete);
                stm.executeUpdate(requete2);
                JOptionPane.showMessageDialog(null, "Effectué");
                this.dispose();

            } catch (HeadlessException | SQLException ex)   {
                JOptionPane.showMessageDialog(null, "erreur 1");
                JOptionPane.showMessageDialog(null, "erreur de suppression \n" + ex.getMessage());

            }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongeModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongeModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongeModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongeModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CongeModif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_im1;
    private javax.swing.JTextField txt_nbr_cong;
    private javax.swing.JLabel txt_nom;
    // End of variables declaration//GEN-END:variables
}
