/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personel;

import java.awt.HeadlessException;
import static java.lang.Float.parseFloat;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class CongeAdd extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    DefaultComboBoxModel model_prenom_conge= new DefaultComboBoxModel();
    
    public CongeAdd() {
        initComponents();
        
         try {
                model_prenom_conge.removeAllElements();
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select nom from perso");
                while (fr.next()){
                    model_prenom_conge.addElement(fr.getString(1));
                }
                comb_prenom_conge.setModel(model_prenom_conge);
            } catch (SQLException e) {
                System.err.println(e);
            }
         
         try {
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select matricul from perso where nom = '"+comb_prenom_conge.getSelectedItem().toString()+"'");
                fr.next();
                txt_im.setText(fr.getString(1));
            } catch (SQLException e) {
                System.err.println(e);
            }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        txt_nbr_cong = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        comb_prenom_conge = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        txt_im = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(334, 399));
        setMinimumSize(new java.awt.Dimension(334, 399));
        setPreferredSize(new java.awt.Dimension(334, 399));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Nombre de jour:");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(10, 170, 129, 34);
        getContentPane().add(txt_nbr_cong);
        txt_nbr_cong.setBounds(150, 170, 169, 34);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Début:");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(10, 220, 71, 34);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(90, 220, 230, 34);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Fin:");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(10, 260, 71, 34);

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(90, 260, 230, 34);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personel/131 copie.png"))); // NOI18N
        jButton11.setText("Ajouter");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(90, 310, 130, 35);

        jButton1.setText("Annuler");
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 310, 90, 35);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        comb_prenom_conge.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comb_prenom_congeItemStateChanged(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Prénom:");

        txt_im.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_im.setForeground(new java.awt.Color(0, 204, 204));
        txt_im.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_im.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_im, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(comb_prenom_conge, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_prenom_conge, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_im, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 340, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comb_prenom_congeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comb_prenom_congeItemStateChanged

        if (comb_prenom_conge.getSelectedItem() == null){

        }else{
            try {

                String nom = comb_prenom_conge.getSelectedItem().toString();
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select matricul from perso where nom='"+nom+"'");
                fr.next();
                txt_im.setText(fr.getString(1));
            } catch (SQLException e) {
                System.err.println(e);
            }

        }
    }//GEN-LAST:event_comb_prenom_congeItemStateChanged

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        if (comb_prenom_conge.getSelectedItem().toString().equals("") || txt_nbr_cong.getText().equals("") 
                || jDateChooser1.getDate().toString().equals("") || jDateChooser2.getDate().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Complétez tous les champs necéssaires!");
        }else{

            String matricul = txt_im.getText();
            String nom = null;
            float cong = 0;
            float conge_rest;
            try {
                ResultSet fr = stm.executeQuery("Select nom,conge from perso where matricul='"+matricul+"'");
                fr.next();
                nom = fr.getString(1);
                cong = fr.getFloat(2);

            } catch (SQLException e) {
                System.err.println(e);
            }

            float nbr_jour = parseFloat(txt_nbr_cong.getText());
            String datedb = String.format("%1$tY-%1$tm-%1$td",jDateChooser1.getDate());
            String datefn = String.format("%1$tY-%1$tm-%1$td",jDateChooser2.getDate());

            conge_rest = cong - nbr_jour;

            String requete = "insert into conge(matricul,nom,nbr_jr,datedebut,datefin)VALUES('"
            + matricul + "','" + nom + "','" + nbr_jour + "','" + datedb+ "','" + datefn+ "')";
            
            String requete2 = "update perso set conge_rest='"+conge_rest+"' where matricul ='"+matricul+"'";

            try {
                stm.executeUpdate(requete);
                stm.executeUpdate(requete2);
                JOptionPane.showMessageDialog(null, "Effectué");
                this.dispose();

            } catch (HeadlessException | SQLException ex)   {
                JOptionPane.showMessageDialog(null, "erreur 1");
                JOptionPane.showMessageDialog(null, "erreur de suppression \n" + ex.getMessage());

            }

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CongeAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comb_prenom_conge;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_im;
    private javax.swing.JTextField txt_nbr_cong;
    // End of variables declaration//GEN-END:variables
}
