/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personel;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author rango
 */
public class fichemploye extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    
    DefaultComboBoxModel combo_prenom_fiche= new DefaultComboBoxModel();
    public fichemploye() {
        initComponents();
        
        
        
        try {
            combo_prenom_fiche.removeAllElements();
            stm = conn.obtenirconnexion().createStatement();
            ResultSet fr = stm.executeQuery("Select nom from perso");
//            
//            if(!fr.next()){
//                combo_prenom_fiche.removeAllElements();
//                combo_prenom_fiche.addElement("-- Aucun personnel --");
//                jComboBox1.setModel(combo_prenom_fiche);
//            }else{
//            combo_prenom_fiche.removeAllElements();
            
            while (fr.next()) {
                combo_prenom_fiche.addElement(fr.getString(1));
            }
//            }
            
        } catch (SQLException e) {
            System.err.println(e);
        }
        jComboBox1.setModel(combo_prenom_fiche);
        
        if (jComboBox1.getSelectedItem().equals("")){
            
        
        }else{
            
            try {
            String prenom = jComboBox1.getSelectedItem().toString();
            stm = conn.obtenirconnexion().createStatement();
            ResultSet fr = stm.executeQuery("Select * from perso where nom = '"+prenom+"'");
            fr.next();
            
            nom.setText(fr.getString("nom"));
            sex.setText(fr.getString("sex"));
            matricul.setText(fr.getString("matricul"));
            cnaps.setText(fr.getString("cnaps"));
            nais.setText(fr.getString("datenais"));
            cat.setText(fr.getString("categori"));
            fonction.setText(fr.getString("fonction"));
            salaire.setText(fr.getString("salaire"));
            embauche.setText(fr.getString("dateemb"));
            tel.setText(fr.getString("tel"));
            adress.setText(fr.getString("adrs"));
            
        } catch (SQLException e) {
            System.err.println(e);
        }
            
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        matricul = new javax.swing.JLabel();
        cat = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        nais = new javax.swing.JLabel();
        salaire = new javax.swing.JLabel();
        embauche = new javax.swing.JLabel();
        adress = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        fonction = new javax.swing.JLabel();
        cnaps = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(400, 551));
        setPreferredSize(new java.awt.Dimension(400, 551));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fiche personnel:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 110, 33);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(127, 0, 260, 33);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 440, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        matricul.setBackground(new java.awt.Color(204, 204, 204));
        matricul.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        matricul.setForeground(new java.awt.Color(0, 0, 102));

        cat.setBackground(new java.awt.Color(204, 204, 204));
        cat.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        cat.setForeground(new java.awt.Color(0, 0, 102));

        sex.setBackground(new java.awt.Color(204, 204, 204));
        sex.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        sex.setForeground(new java.awt.Color(0, 0, 102));

        nais.setBackground(new java.awt.Color(204, 204, 204));
        nais.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        nais.setForeground(new java.awt.Color(0, 0, 102));

        salaire.setBackground(new java.awt.Color(204, 204, 204));
        salaire.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        salaire.setForeground(new java.awt.Color(0, 0, 102));

        embauche.setBackground(new java.awt.Color(204, 204, 204));
        embauche.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        embauche.setForeground(new java.awt.Color(0, 0, 102));

        adress.setBackground(new java.awt.Color(204, 204, 204));
        adress.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        adress.setForeground(new java.awt.Color(0, 0, 102));

        nom.setBackground(new java.awt.Color(204, 204, 204));
        nom.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(0, 0, 102));

        fonction.setBackground(new java.awt.Color(204, 204, 204));
        fonction.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        fonction.setForeground(new java.awt.Color(0, 0, 102));

        cnaps.setBackground(new java.awt.Color(204, 204, 204));
        cnaps.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        cnaps.setForeground(new java.awt.Color(0, 0, 102));

        tel.setBackground(new java.awt.Color(204, 204, 204));
        tel.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        tel.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matricul, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnaps, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nais, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fonction, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(embauche, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(matricul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(cnaps, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(nais, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(fonction, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(embauche, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 50, 300, 560);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom/Prénom:");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Sex:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Immatriculation:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("N° CNAPS:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date de naissance:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Catégorie:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fonction:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Salaire de base:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date d'embauche:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Téléphone:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Adresse:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 440, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (jComboBox1.getSelectedItem().equals("-- Aucun personnel --")){
        
        
        }else{
            
            try {
            String prenom = jComboBox1.getSelectedItem().toString();
            stm = conn.obtenirconnexion().createStatement();
            ResultSet fr = stm.executeQuery("Select * from perso where nom = '"+prenom+"'");
            fr.next();

            nom.setText(fr.getString("nom"));
            sex.setText(fr.getString("sex"));
            matricul.setText(fr.getString("matricul"));
            cnaps.setText(fr.getString("cnaps"));
            nais.setText(fr.getString("datenais"));
            cat.setText(fr.getString("categori"));
            fonction.setText(fr.getString("fonction"));
            salaire.setText(fr.getString("salaire"));
            embauche.setText(fr.getString("dateemb"));
            tel.setText(fr.getString("tel"));
            adress.setText(fr.getString("adrs"));
            
            
        } catch (SQLException e) {
            System.err.println(e);
        }
            
            
        }
        
        
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fichemploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fichemploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fichemploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fichemploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fichemploye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adress;
    private javax.swing.JLabel cat;
    private javax.swing.JLabel cnaps;
    private javax.swing.JLabel embauche;
    private javax.swing.JLabel fonction;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel matricul;
    private javax.swing.JLabel nais;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel salaire;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel tel;
    // End of variables declaration//GEN-END:variables
}
