/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

import java.awt.HeadlessException;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.*;
import java.awt.print.*;
import static java.lang.Float.parseFloat;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.Timer;

/**
 *
 * @author rango
 */
public class AjoutFournisseur extends javax.swing.JFrame {

   conect conn = new conect();
        Statement stm;
        ResultSet Rs;
        Statement a;
    public AjoutFournisseur() {
        
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAjoutFournisseurID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAjoutFournisseurDesignation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAjoutFournisseurTel = new javax.swing.JTextField();
        txtAjoutFournisseurMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAjoutFournisseurAdress = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAjoutFournisseurAjout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(448, 449));
        setMinimumSize(new java.awt.Dimension(448, 449));
        setPreferredSize(new java.awt.Dimension(448, 449));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("VertigoFLF", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nouveau fournisseur");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 200, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-60, 0, 242, 60);

        jLabel11.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 70, 129, 34);

        txtAjoutFournisseurID.setText("Fxxx");
        txtAjoutFournisseurID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        getContentPane().add(txtAjoutFournisseurID);
        txtAjoutFournisseurID.setBounds(190, 70, 217, 32);

        jLabel3.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Désignation:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 129, 34);

        txtAjoutFournisseurDesignation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        getContentPane().add(txtAjoutFournisseurDesignation);
        txtAjoutFournisseurDesignation.setBounds(190, 110, 217, 32);

        jLabel4.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tel:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 129, 34);

        txtAjoutFournisseurTel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        getContentPane().add(txtAjoutFournisseurTel);
        txtAjoutFournisseurTel.setBounds(190, 150, 217, 32);

        txtAjoutFournisseurMail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        getContentPane().add(txtAjoutFournisseurMail);
        txtAjoutFournisseurMail.setBounds(190, 190, 217, 32);

        jLabel5.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 190, 129, 34);

        jLabel6.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adresse:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 230, 129, 34);

        txtAjoutFournisseurAdress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        txtAjoutFournisseurAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAjoutFournisseurAdressActionPerformed(evt);
            }
        });
        getContentPane().add(txtAjoutFournisseurAdress);
        txtAjoutFournisseurAdress.setBounds(190, 230, 217, 32);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        btnAjoutFournisseurAjout.setBackground(java.awt.SystemColor.windowText);
        btnAjoutFournisseurAjout.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAjoutFournisseurAjout.setForeground(new java.awt.Color(255, 255, 255));
        btnAjoutFournisseurAjout.setText("Enregistrer");
        btnAjoutFournisseurAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutFournisseurAjoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnAjoutFournisseurAjout);
        btnAjoutFournisseurAjout.setBounds(120, 370, 140, 40);

        jButton1.setBackground(java.awt.SystemColor.windowText);
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 370, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personel/Capture3 copie2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 450);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutFournisseurAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutFournisseurAjoutActionPerformed

        try{

            if (txtAjoutFournisseurID.getText().length() == 0 ||txtAjoutFournisseurDesignation.getText().length() == 0 || txtAjoutFournisseurAdress.getText().length() == 0 || txtAjoutFournisseurTel.getText().length() == 0 || txtAjoutFournisseurMail.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "Veuillez completer tous les champs!");
            }

            else   {

                String id = txtAjoutFournisseurID.getText();
                String designation = txtAjoutFournisseurDesignation.getText();
                String tel = txtAjoutFournisseurTel.getText();
                String mail = txtAjoutFournisseurMail.getText();
                String adress = txtAjoutFournisseurAdress.getText();
                //String categori = (String) comboAjoutProduitcategori.getSelectedItem();
                
                stm = conn.obtenirconnexion().createStatement();
                //String id = txtAjoutProduitID.getText();
                ResultSet fr = stm.executeQuery("Select id,designation from fournisseur where id='"+id+"'");

                if (fr.next()) {

                    JOptionPane.showMessageDialog(null, id+" ("+fr.getString(2)+") existe déjà!");

                }else {
                    //prixunit = parseFloat(txtAjoutProduitprixunit.getText());
                    try {

                        stm = conn.obtenirconnexion().createStatement();
                        String requete = "insert into fournisseur(id,designation,tel,mail,adress)VALUES('" + id + "','"
                        + designation + "','" + tel + "','" + mail + "','" + adress + "')";
                        stm.executeUpdate(requete);
                        JOptionPane.showMessageDialog(null, "Fournisseur ajouté");

                        this.dispose();
                        //this.dispose();

                    } catch (HeadlessException | SQLException ex)   {

                    }}

                }
            }catch (HeadlessException | SQLException ex) {
            }

    }//GEN-LAST:event_btnAjoutFournisseurAjoutActionPerformed

    private void txtAjoutFournisseurAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAjoutFournisseurAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAjoutFournisseurAdressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutFournisseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutFournisseurAjout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAjoutFournisseurAdress;
    private javax.swing.JTextField txtAjoutFournisseurDesignation;
    private javax.swing.JTextField txtAjoutFournisseurID;
    private javax.swing.JTextField txtAjoutFournisseurMail;
    private javax.swing.JTextField txtAjoutFournisseurTel;
    // End of variables declaration//GEN-END:variables
}
