/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class AjoutFacture extends javax.swing.JFrame {

    conect conn = new conect();
        Statement stm;
        ResultSet Rs;
        Statement a;
        
        DefaultComboBoxModel com_fournisseur = new DefaultComboBoxModel();
        
        
    public AjoutFacture() {
        initComponents();
        
           try {
            com_fournisseur.removeAllElements();
            stm = conn.obtenirconnexion().createStatement();
            ResultSet fr = stm.executeQuery("Select designation from fournisseur");
            while (fr.next()) {
                com_fournisseur.addElement(fr.getString(1));
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        comb_fourni_fac.setModel(com_fournisseur);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_ajout_fac = new javax.swing.JButton();
        txt_datelimit_fac = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_dateaq_fac = new com.toedter.calendar.JDateChooser();
        comb_fourni_fac = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_des_fac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(429, 412));
        setMinimumSize(new java.awt.Dimension(429, 412));
        setPreferredSize(new java.awt.Dimension(429, 412));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("VertigoFLF", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nouvelle facture");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 160, 40);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jButton1.setBackground(java.awt.SystemColor.windowText);
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 350, 100, 40);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-80, 10, 242, 40);

        btn_ajout_fac.setBackground(java.awt.SystemColor.windowText);
        btn_ajout_fac.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_ajout_fac.setForeground(new java.awt.Color(255, 255, 255));
        btn_ajout_fac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/131 copie.png"))); // NOI18N
        btn_ajout_fac.setText("Enregistrer");
        btn_ajout_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajout_facActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ajout_fac);
        btn_ajout_fac.setBounds(70, 350, 143, 40);

        txt_datelimit_fac.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        txt_datelimit_fac.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txt_datelimit_fac);
        txt_datelimit_fac.setBounds(217, 249, 143, 29);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Date limite");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(68, 242, 143, 28);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date d'acquisition:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(68, 204, 143, 26);

        txt_dateaq_fac.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        txt_dateaq_fac.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txt_dateaq_fac);
        txt_dateaq_fac.setBounds(217, 203, 143, 30);

        comb_fourni_fac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fournisseur 1", "Fournisseur 2" }));
        comb_fourni_fac.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        jPanel1.add(comb_fourni_fac);
        comb_fourni_fac.setBounds(217, 148, 143, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fournisseur:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(68, 146, 143, 26);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Designation:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(68, 96, 118, 26);

        txt_des_fac.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        jPanel1.add(txt_des_fac);
        txt_des_fac.setBounds(217, 96, 143, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personel/Capture3 copie2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 430, 410);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajout_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajout_facActionPerformed

        String designation = txt_des_fac.getText();
        String fournisseur = (String) comb_fourni_fac.getSelectedItem();
        String c = String.format("%1$tY-%1$tm-%1$td",txt_dateaq_fac.getDate());
        String d = String.format("%1$tY-%1$tm-%1$td",txt_datelimit_fac.getDate());

        String requete = "insert into facture(designation,fournisseur,dateAcqui,datePayemn,etat,etat2)VALUES('"
        + designation + "','" + fournisseur + "','" + c
        + "','" + d + "','non','ouvert')";
        try{

            if (txt_des_fac.getText().length() == 0 || txt_dateaq_fac.getDate().toString().length() == 0 ||
                txt_datelimit_fac.getDate().toString().length() == 0 ) {
                JOptionPane.showMessageDialog(null, "Veuillez completer tous les champs!");
            }

            else   {
                String des = txt_des_fac.getText();
                ResultSet fr = stm.executeQuery("Select * from facture where designation='"+des+"'");

                if (fr.next()) {

                    JOptionPane.showMessageDialog(null, des+" existe déjà!");

                }else {

                    try {
                        stm.executeUpdate(requete);
                        JOptionPane.showMessageDialog(null, "Nouvelle facture ajouté");
//                        txt_des_fac.setText("");
//                        txt_dateaq_fac.setDate(null);
//                        txt_datelimit_fac.setDate(null);

                        //afficher_fac_mouv();
                        //deplace_combobox_facture_entrer();
                         this.setVisible(false);
                    } catch (HeadlessException | SQLException ex)   {
                        JOptionPane.showMessageDialog(null, "erreur 1");
                    }}

                }//afficher_fac_mouv();
            }catch (HeadlessException | SQLException ex) {

                JOptionPane.showMessageDialog(null, "arreur 2");

            }
    }//GEN-LAST:event_btn_ajout_facActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutFacture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajout_fac;
    private javax.swing.JComboBox comb_fourni_fac;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser txt_dateaq_fac;
    private com.toedter.calendar.JDateChooser txt_datelimit_fac;
    private javax.swing.JTextField txt_des_fac;
    // End of variables declaration//GEN-END:variables
}
