/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rango
 */
public class Client extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm,stm1;
    ResultSet Rs;
    
    public String selected_cli;
    
    DefaultTableModel model_client = new DefaultTableModel();
    public Client() {
        initComponents();
        
        afficher_client();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_client = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnClientSuppr = new javax.swing.JButton();
        btnClientModif = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtClientTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_menuPrincial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(889, 542));
        setMinimumSize(new java.awt.Dimension(889, 542));
        setPreferredSize(new java.awt.Dimension(889, 542));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        tbl_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Prénom/Nom", "Tel", "Adresse", "Mail"
            }
        ));
        tbl_client.setRowHeight(30);
        tbl_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_client);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 127, 869, 381);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 84, 172, 37);

        btnClientSuppr.setText("Supprimer");
        btnClientSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientSupprActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientSuppr);
        btnClientSuppr.setBounds(707, 84, 172, 37);

        btnClientModif.setText("Modifier");
        btnClientModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientModifActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientModif);
        btnClientModif.setBounds(525, 84, 172, 37);

        jLabel1.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Client");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-130, 10, 240, 40);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        txtClientTotal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtClientTotal.setForeground(new java.awt.Color(0, 204, 204));
        txtClientTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOTAL:");

        btn_menuPrincial.setBackground(java.awt.Color.black);
        btn_menuPrincial.setForeground(new java.awt.Color(255, 255, 255));
        btn_menuPrincial.setText("Menus principal");
        btn_menuPrincial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuPrincialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtClientTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                .addComponent(btn_menuPrincial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_menuPrincial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtClientTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void afficher_client() {
        model_client.setColumnCount(0);
        model_client.addColumn("ID");
        model_client.addColumn("Prénom/Nom");
        model_client.addColumn("Téléphone");
        model_client.addColumn("Adresse");
        model_client.addColumn("E-mail");
        
        btnClientModif.setEnabled(false);
        btnClientSuppr.setEnabled(false);
    
        try {
                model_client.setRowCount(0);
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select * from client order by id_client");
                    while (fr.next())   {
                        model_client.addRow(new Object[]{fr.getString("id_client"),fr.getString("nom_client"),
                            fr.getString("tel_client"), fr.getString("adresse"), fr.getString("mail")});
                                        }
            } catch (SQLException e) {System.err.println(e);}
        
        tbl_client.setModel(model_client);
        
        
        try {
                stm1 = conn.obtenirconnexion().createStatement();
                ResultSet fr2 = stm.executeQuery("Select count(*) from client");
                fr2.next();
                txtClientTotal.setText(fr2.getString(1));
               
                                        
            } catch (SQLException e) {System.err.println(e);}

}
    
    
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        login.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClientAdd cli = new ClientAdd();
        cli.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnClientModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientModifActionPerformed
       ClientModif cli = new ClientModif();
        cli.setVisible(true);
   
    }//GEN-LAST:event_btnClientModifActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        afficher_client();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tbl_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientMouseClicked
        
        btnClientModif.setEnabled(true);
        btnClientSuppr.setEnabled(true);
        
        int select = tbl_client.getSelectedRow();
        selected_cli = tbl_client.getValueAt(select, 0).toString();
        
    }//GEN-LAST:event_tbl_clientMouseClicked

    private void btnClientSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientSupprActionPerformed
        int i = tbl_client.getSelectedRow();
        String id = tbl_client.getValueAt(i, 0).toString();
        
            try {
                if (JOptionPane.showConfirmDialog(null, "voulez-vous vraiment supprimer: "+id+" ?" , "supprimer le client",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                if (id.length() != 0) {
                    stm.executeUpdate("Delete From client where id_client = '" + id+"'");
                    JOptionPane.showMessageDialog(null, "\""+id +"\" supprimé de la liste!");
                    //afficher_table();
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Veuillez remplire le champ Numero");
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de suppression \n" + e.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_btnClientSupprActionPerformed

    private void btn_menuPrincialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuPrincialActionPerformed
        login.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menuPrincialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientModif;
    private javax.swing.JButton btnClientSuppr;
    private javax.swing.JButton btn_menuPrincial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_client;
    private javax.swing.JLabel txtClientTotal;
    // End of variables declaration//GEN-END:variables
}
