/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class ClientAdd extends javax.swing.JFrame {

    
    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    public ClientAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClientAjoutID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClientAjoutNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClientAjoutTel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClientAjoutMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtClientAjoutAdress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnClientAjout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(399, 403));
        setMinimumSize(new java.awt.Dimension(399, 403));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 62, 125, 40);
        getContentPane().add(txtClientAjoutID);
        txtClientAjoutID.setBounds(158, 62, 198, 40);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prenom/Nom:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 108, 125, 40);
        getContentPane().add(txtClientAjoutNom);
        txtClientAjoutNom.setBounds(158, 108, 198, 40);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tel:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 154, 125, 40);
        getContentPane().add(txtClientAjoutTel);
        txtClientAjoutTel.setBounds(158, 154, 198, 40);

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(23, 200, 125, 40);
        getContentPane().add(txtClientAjoutMail);
        txtClientAjoutMail.setBounds(158, 200, 198, 40);

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adresse:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(23, 246, 125, 40);
        getContentPane().add(txtClientAjoutAdress);
        txtClientAjoutAdress.setBounds(158, 246, 198, 40);

        jLabel6.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ajout");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 10, 80, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-130, 10, 240, 40);

        btnClientAjout.setText("Ajouter");
        btnClientAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientAjoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientAjout);
        btnClientAjout.setBounds(192, 304, 121, 42);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientAjoutActionPerformed
         try{

            if (txtClientAjoutID.getText().length() == 0 ||txtClientAjoutNom.getText().length() == 0 || txtClientAjoutTel.getText().length() == 0 
                    || txtClientAjoutMail.getText().length() == 0 || txtClientAjoutAdress.getText().length() == 0){
                
                JOptionPane.showMessageDialog(null, "Veuillez completer tous les champs!");
            }

            else   {
                
                    String id = txtClientAjoutID.getText();
                    String nom = txtClientAjoutNom.getText();
                    String tel = txtClientAjoutTel.getText();
                    String mail = txtClientAjoutMail.getText();
                    String adress = txtClientAjoutAdress.getText();
                
                stm = conn.obtenirconnexion().createStatement();
                //String id = txtAjoutProduitID.getText();
                ResultSet fr = stm.executeQuery("Select id_client,nom_client from client where id_client='"+id+"'");

                if (fr.next()) {

                    JOptionPane.showMessageDialog(null, fr.getString(2)+" existe déjà!");

                }else {
                    //prixunit = parseFloat(txtAjoutProduitprixunit.getText());
                    try {
                        
                     
                    stm = conn.obtenirconnexion().createStatement();
                    String requete = "insert into client(id_client,nom_client,tel_client,adresse,mail)VALUES('" + id + "','" 
                + nom + "','" + tel + "','" + adress + "','" + mail + "')";
                    stm.executeUpdate(requete);
                    JOptionPane.showMessageDialog(null, "Client ajouté");
                    
                    
                    this.dispose();
                    //this.dispose();

                } catch (HeadlessException | SQLException ex)   {
                    
                }}

            } 
        }catch (HeadlessException | SQLException ex) {
        }
    }//GEN-LAST:event_btnClientAjoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientAjout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtClientAjoutAdress;
    private javax.swing.JTextField txtClientAjoutID;
    private javax.swing.JTextField txtClientAjoutMail;
    private javax.swing.JTextField txtClientAjoutNom;
    private javax.swing.JTextField txtClientAjoutTel;
    // End of variables declaration//GEN-END:variables
}
