/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class ClientModif extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    String id_cli = MenuPrincipal.cli.selected_cli;
    
    public ClientModif() {
        initComponents();
        
        txtClientModifID.setText(id_cli);
        txtClientModifID.setEditable(false);
       
        try{
                stm = conn.obtenirconnexion().createStatement();
                //String des = txtModifProduitDesignation.getText();
                ResultSet fr = stm.executeQuery("Select * from client where id_client ='"+id_cli+"'");

                fr.next();

                        txtClientModifNom.setText(fr.getString(3));
                        txtClientModifTel.setText(fr.getString(4));
                        txtClientModifAdress.setText(fr.getString(5));
                        txtClientModifMail.setText(fr.getString(6));

                //}else { }

                
            }catch (HeadlessException | SQLException ex) {
            }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClientModifID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClientModifNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClientModifTel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClientModifMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtClientModifAdress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnClientModif = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 399));
        setMinimumSize(new java.awt.Dimension(400, 399));
        setPreferredSize(new java.awt.Dimension(400, 399));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 62, 125, 40);
        getContentPane().add(txtClientModifID);
        txtClientModifID.setBounds(158, 62, 198, 40);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prenom/Nom:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 108, 125, 40);
        getContentPane().add(txtClientModifNom);
        txtClientModifNom.setBounds(158, 108, 198, 40);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tel:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 154, 125, 40);
        getContentPane().add(txtClientModifTel);
        txtClientModifTel.setBounds(158, 154, 198, 40);

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(23, 200, 125, 40);
        getContentPane().add(txtClientModifMail);
        txtClientModifMail.setBounds(158, 200, 198, 40);

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adresse:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(23, 246, 125, 40);
        getContentPane().add(txtClientModifAdress);
        txtClientModifAdress.setBounds(158, 246, 198, 40);

        jLabel6.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modification");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 10, 130, 40);

        btnClientModif.setText("Modifier");
        btnClientModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientModifActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientModif);
        btnClientModif.setBounds(192, 304, 121, 42);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-70, 10, 240, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientModifActionPerformed
        
        try {
                //String b = txtModifProduitID.getText();
                if (JOptionPane.showConfirmDialog(null, "modification sur le client: "+id_cli , "modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                stm.executeUpdate("UPDATE client SET nom_client='" + txtClientModifNom.getText() + "',tel_client='" + txtClientModifTel.getText()
                    + "',adresse='" + txtClientModifAdress.getText()+ "',mail='" + txtClientModifMail.getText()
                    + "' WHERE id_client='" + id_cli+"'");
                JOptionPane.showMessageDialog(null, "Succès!");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de modification !" + e.getMessage());
            System.err.println(e);
        }
        
        this.dispose();
        
        
    }//GEN-LAST:event_btnClientModifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientModif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientModif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtClientModifAdress;
    private javax.swing.JTextField txtClientModifID;
    private javax.swing.JTextField txtClientModifMail;
    private javax.swing.JTextField txtClientModifNom;
    private javax.swing.JTextField txtClientModifTel;
    // End of variables declaration//GEN-END:variables
}
