/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class menuModif extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    String id_menu = MenuPrincipal.menu.selected_menu;
    
    public menuModif() {
        initComponents();
        
        
        txtMenuModif.setText(id_menu);
        txtMenuModif.setEditable(false);
       
        try{
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select * from menu where id ='"+id_menu+"'");

                fr.next();

                        txtMenuModifDes.setText(fr.getString(2));
                        comMenuModifCategori.setSelectedItem(fr.getString(3));
                        txtMenuModifPU.setText(fr.getString(4));
 
            }catch (HeadlessException | SQLException ex) {
            }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnMenuAjout = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMenuModif = new javax.swing.JTextField();
        txtMenuModifDes = new javax.swing.JTextField();
        comMenuModifCategori = new javax.swing.JComboBox();
        txtMenuModifPU = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(430, 450));
        setMinimumSize(new java.awt.Dimension(430, 450));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modification");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 130, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-60, 10, 242, 40);

        btnMenuAjout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/modif.PNG"))); // NOI18N
        btnMenuAjout.setText("Modifier");
        btnMenuAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAjoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuAjout);
        btnMenuAjout.setBounds(210, 360, 143, 33);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("P.U:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(70, 260, 130, 28);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Catégorie:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(68, 210, 145, 26);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Designation:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(68, 152, 145, 26);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(68, 101, 118, 26);

        txtMenuModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenuModifActionPerformed(evt);
            }
        });
        jPanel1.add(txtMenuModif);
        txtMenuModif.setBounds(200, 102, 160, 26);
        jPanel1.add(txtMenuModifDes);
        txtMenuModifDes.setBounds(200, 150, 160, 30);

        comMenuModifCategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boissons chaudes", "Boissons fraiches", "Bières", "Vins - Apéritifs", "Whiskys - Alcools", "Liqueurs - Digestifs", "Champagne", "Cocktails", "Salades", "Entréés", "Tartares", "Woks", "Poissons", "Humbergers", "Pates", "Soupes", "Viandes" }));
        jPanel1.add(comMenuModifCategori);
        comMenuModifCategori.setBounds(200, 210, 160, 30);
        jPanel1.add(txtMenuModifPU);
        txtMenuModifPU.setBounds(200, 260, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAjoutActionPerformed
        try {
                //String b = txtModifProduitID.getText();
                if (JOptionPane.showConfirmDialog(null, "modification sur le client: "+txtMenuModifDes.getText() , "modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                stm.executeUpdate("UPDATE menu SET designation='" + txtMenuModifDes.getText() + "',categorie='" + comMenuModifCategori.getSelectedItem().toString()
                    + "',pu='" + txtMenuModifPU.getText()
                    + "' WHERE id='" + id_menu+"'");
                
                stm.executeUpdate("UPDATE commande SET des_menu ='" + txtMenuModifDes.getText() + "' WHERE id_menu ='" + id_menu+"'");
                
                JOptionPane.showMessageDialog(null, "Succès!");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de modification !" + e.getMessage());
            System.err.println(e);
        }
        
        this.dispose();
        
    }//GEN-LAST:event_btnMenuAjoutActionPerformed

    private void txtMenuModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenuModifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuModif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuAjout;
    private javax.swing.JComboBox comMenuModifCategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMenuModif;
    private javax.swing.JTextField txtMenuModifDes;
    private javax.swing.JTextField txtMenuModifPU;
    // End of variables declaration//GEN-END:variables
}
