/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class menuIngredientAjout extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    String id_menu = MenuPrincipal.menu.selected_menu;
    DefaultComboBoxModel prod = new DefaultComboBoxModel();
    
    public menuIngredientAjout() {
        initComponents();
  
        try{
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select designation from menu where id ='"+id_menu+"'");

                fr.next();

                txtMenu.setText(fr.getString("designation"));
 
            }catch (HeadlessException | SQLException ex) {
            }
        
        

        //COMBOBOX PRODUIT
        try{
                prod.removeAllElements();
                comProduit.removeAllItems();
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select designation from produit");

                while (fr.next()) {
                    prod.addElement(fr.getString("designation"));
                    
                }
                comProduit.setModel(prod);
            }catch (HeadlessException | SQLException ex) {
            }
        //---------------------------
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comProduit = new javax.swing.JComboBox();
        comCategorie = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMenu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(646, 322));
        setMinimumSize(new java.awt.Dimension(646, 322));
        setPreferredSize(new java.awt.Dimension(646, 322));
        setResizable(false);
        getContentPane().setLayout(null);

        comProduit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comProduit);
        comProduit.setBounds(326, 186, 310, 36);

        comCategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choisir catégorie", "Boisson non alcolique", "Boisson alcolique", "Boisson chaud", "Boisson (sirop)", "Charcuteries", "Condiments", "Fromages", "Fruits", "Féculents", "Légumes", "Oeufs", "Poudres", "Viandes", "Crèmerie", "Poisson", "Epicerie", "Materiels de cuisine" }));
        comCategorie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comCategorieItemStateChanged(evt);
            }
        });
        getContentPane().add(comCategorie);
        comCategorie.setBounds(10, 186, 310, 36);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ajout ingrédient");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 10, 160, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-20, 10, 242, 40);

        txtMenu.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        txtMenu.setForeground(new java.awt.Color(0, 204, 204));
        txtMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMenu.setText("Designation du menu");
        jPanel1.add(txtMenu);
        txtMenu.setBounds(90, 70, 350, 36);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Menu:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 80, 36);

        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 250, 173, 39);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 250, 173, 39);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingredient");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 140, 110, 36);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comCategorieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comCategorieItemStateChanged
        if (comCategorie.getSelectedItem().equals("Choisir catégorie")){
            try{
                prod.removeAllElements();
                comProduit.removeAllItems();
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select designation from produit order by designation");

                while (fr.next()) {
                    prod.addElement(fr.getString("designation"));
                    
                }
 
            }catch (HeadlessException | SQLException ex) {
            }
            
        }else{
            
            try{
                prod.removeAllElements();
                comProduit.removeAllItems();
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select designation from produit where categori = '"+comCategorie.getSelectedItem().toString()+"'");

                while (fr.next()) {
                    prod.addElement(fr.getString("designation"));
                    
                }
 
            }catch (HeadlessException | SQLException ex) {
            }
            
        }
        
        
        
    }//GEN-LAST:event_comCategorieItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{

            if (comProduit.getSelectedItem().toString().length() == 0 ){
                
                JOptionPane.showMessageDialog(null, "Veuillez selectionner le produit!");
            }

            else   {
                
                    String id_men = id_menu;
                    String des_menu = txtMenu.getText();
                    String id_prod = null;
                    try{
                        stm = conn.obtenirconnexion().createStatement();
                        ResultSet fr = stm.executeQuery("Select id from produit where designation ='"+comProduit.getSelectedItem().toString()+"'");

                        fr.next();

                        id_prod = fr.getString("id");

                        }catch (HeadlessException | SQLException ex) {
                        }
                    String des_prod = comProduit.getSelectedItem().toString();
     
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr2 = stm.executeQuery("Select id_menu,id_produit from ingredient where id_menu='"+id_menu+"' && id_produit='"+id_prod+"' ");

                if (fr2.next()) {

                    JOptionPane.showMessageDialog(null, comProduit.getSelectedItem().toString()+" existe déjà dans: "+des_menu);

                }else {
                    //prixunit = parseFloat(txtAjoutProduitprixunit.getText());
                    try {
                        
                     
                    stm = conn.obtenirconnexion().createStatement();
                    String requete = "insert into ingredient(id_menu,des_menu,id_produit,des_produit)VALUES('" + id_men + "','" 
                + des_menu + "','" + id_prod + "','" + des_prod + "')";
                    stm.executeUpdate(requete);
                    
                    JOptionPane.showMessageDialog(null, "Ingrédient ajouté");

                } catch (HeadlessException | SQLException ex)   {
                    
                }}

            } 
        }catch (HeadlessException | SQLException ex) {
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuIngredientAjout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuIngredientAjout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuIngredientAjout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuIngredientAjout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuIngredientAjout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comCategorie;
    private javax.swing.JComboBox comProduit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtMenu;
    // End of variables declaration//GEN-END:variables
}
