/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class ModifFacture extends javax.swing.JFrame {

    conect conn = new conect();
        Statement stm;
        ResultSet Rs;
        Statement a;
        
        DefaultComboBoxModel com_facture_fournisseur = new DefaultComboBoxModel();
        public String selected_fac = MenuPrincipal.mainAp.selected_facture;
        
    public ModifFacture() {
        initComponents();
        txtModifFactureDesignation.setText(selected_fac);
        txtModifFactureDesignation.setEditable(false);
        
        try {
            com_facture_fournisseur.removeAllElements();
            stm = conn.obtenirconnexion().createStatement();
            ResultSet fr = stm.executeQuery("Select designation from fournisseur");
            while (fr.next()) {
                com_facture_fournisseur.addElement(fr.getString(1));
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        comModifFactureFournisseur.setModel(com_facture_fournisseur);
        
        
        try{
                stm = conn.obtenirconnexion().createStatement();
                //String des = txtModifProduitDesignation.getText();
                ResultSet fr = stm.executeQuery("Select * from facture where designation ='"+selected_fac+"'");

                fr.next();

                        comModifFactureFournisseur.setSelectedItem(fr.getString(3));
                        
                        ModifFactureDateacqui.setDate(fr.getDate(4));
                        dateModifFactureLimite.setDate(fr.getDate(5));
                        //txtModifFournisseurAdress.setText(fr.getString(6));
                        

                //}else { }

                
            }catch (HeadlessException | SQLException ex) {
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnModifFactureModif = new javax.swing.JButton();
        dateModifFactureLimite = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ModifFactureDateacqui = new com.toedter.calendar.JDateChooser();
        comModifFactureFournisseur = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtModifFactureDesignation = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(428, 419));
        setMinimumSize(new java.awt.Dimension(428, 419));
        setPreferredSize(new java.awt.Dimension(428, 419));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modification");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 130, 40);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-70, 10, 242, 40);

        btnModifFactureModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/131 copie.png"))); // NOI18N
        btnModifFactureModif.setText("Mettre à jour");
        btnModifFactureModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifFactureModifActionPerformed(evt);
            }
        });
        jPanel1.add(btnModifFactureModif);
        btnModifFactureModif.setBounds(217, 335, 143, 33);

        dateModifFactureLimite.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dateModifFactureLimite);
        dateModifFactureLimite.setBounds(217, 249, 143, 29);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Date limite");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(68, 247, 145, 28);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date d'acquisition:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(68, 210, 145, 26);

        ModifFactureDateacqui.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(ModifFactureDateacqui);
        ModifFactureDateacqui.setBounds(217, 203, 143, 30);

        comModifFactureFournisseur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fournisseur 1", "Fournisseur 2" }));
        jPanel1.add(comModifFactureFournisseur);
        comModifFactureFournisseur.setBounds(217, 155, 143, 23);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fournisseur:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(68, 152, 145, 26);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Designation:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(68, 101, 118, 26);
        jPanel1.add(txtModifFactureDesignation);
        txtModifFactureDesignation.setBounds(217, 102, 143, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifFactureModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifFactureModifActionPerformed

        

        try {
            
            if (JOptionPane.showConfirmDialog(null, "modification sur de la facture: "+selected_fac , "modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                try {
                    String c = String.format("%1$tY-%1$tm-%1$td",ModifFactureDateacqui.getDate());
                    String d = String.format("%1$tY-%1$tm-%1$td",dateModifFactureLimite.getDate());
                    stm.executeUpdate("UPDATE facture SET fournisseur='" + comModifFactureFournisseur.getSelectedItem() + "',dateAcqui='" + c
                            + "',datePayemn='" + d + "' WHERE designation='" + selected_fac+"'");
                } catch (SQLException ex) {
                    Logger.getLogger(ModifFournisseur.class.getName()).log(Level.SEVERE, null, ex);
                }
            JOptionPane.showMessageDialog(null, "Succès!");
        }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "erreur de modification !" + e.getMessage());
            System.err.println(e);
        }

        this.dispose();
    }//GEN-LAST:event_btnModifFactureModifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifFacture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ModifFactureDateacqui;
    private javax.swing.JButton btnModifFactureModif;
    private javax.swing.JComboBox comModifFactureFournisseur;
    private com.toedter.calendar.JDateChooser dateModifFactureLimite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtModifFactureDesignation;
    // End of variables declaration//GEN-END:variables
}
