/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import static java.lang.Float.parseFloat;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class ModifProduct extends javax.swing.JFrame {

    
    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    String test;
    
    public String selected = MenuPrincipal.mainAp.selected;
    
    public ModifProduct() {
        initComponents();
        txtModifProduitID.setText(selected);
        txtModifProduitID.setEditable(false);
        try{
                stm = conn.obtenirconnexion().createStatement();
                //String des = txtModifProduitDesignation.getText();
                ResultSet fr = stm.executeQuery("Select * from produit where id ='"+selected+"'");

                fr.next();

                        txtModifProduitDesignation.setText(fr.getString(3));
                        txtModifProduitqteactu.setText(fr.getString(4));
                        txtModifProduitqtealert.setText(fr.getString(5));
                        comboModifunitemesure.setSelectedItem(fr.getString(6));
                        txtModifProduitprixUnitaire.setText(fr.getString(7));
                        comboModifCategori.setSelectedItem(fr.getString(8));

                //}else { }

                
            }catch (HeadlessException | SQLException ex) {
            }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtModifProduitDesignation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtModifProduitqteactu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtModifProduitqtealert = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboModifunitemesure = new javax.swing.JComboBox();
        txtModifProduitprixUnitaire = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboModifCategori = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtAjoutProduitimage = new javax.swing.JLabel();
        btnModifModif = new javax.swing.JButton();
        txtModifProduitID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(440, 510));
        setMinimumSize(new java.awt.Dimension(440, 510));
        setPreferredSize(new java.awt.Dimension(440, 510));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modification");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 170, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 10, 240, 50);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);
        jPanel1.add(txtModifProduitDesignation);
        txtModifProduitDesignation.setBounds(170, 110, 217, 32);

        jLabel3.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Désignation:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 129, 34);

        jLabel4.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qté actuelle:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 129, 34);
        jPanel1.add(txtModifProduitqteactu);
        txtModifProduitqteactu.setBounds(170, 150, 217, 32);

        jLabel5.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Qté d'alert:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 190, 129, 34);
        jPanel1.add(txtModifProduitqtealert);
        txtModifProduitqtealert.setBounds(170, 190, 217, 32);

        jLabel6.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Unité de mesure:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 230, 129, 34);

        comboModifunitemesure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ariary", "Litre", "Sachet", "Bocal", "Boite", "Paquet", "Pièce", "Botte", "Kapoaka", "Brique", "Carton", "Barquette", "Kg", "Bouteille" }));
        jPanel1.add(comboModifunitemesure);
        comboModifunitemesure.setBounds(170, 230, 217, 34);
        jPanel1.add(txtModifProduitprixUnitaire);
        txtModifProduitprixUnitaire.setBounds(170, 270, 217, 32);

        jLabel7.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prix unitaire (en Ar):");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 270, 129, 34);

        jLabel8.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Catégorie:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 310, 129, 34);

        comboModifCategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boisson non alcolique", "Boisson alcolique", "Boisson chaud", "Boisson (sirop)", "Charcuteries", "Condiments", "Fromages", "Fruits", "Féculents", "Légumes", "Oeufs", "Poudres", "Viandes", "Crèmerie", "Poisson", "Epicerie", "Materiels de cuisine" }));
        jPanel1.add(comboModifCategori);
        comboModifCategori.setBounds(170, 310, 219, 34);

        jLabel9.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Photo:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 350, 130, 34);
        jPanel1.add(txtAjoutProduitimage);
        txtAjoutProduitimage.setBounds(170, 360, 220, 50);

        btnModifModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/valider.PNG"))); // NOI18N
        btnModifModif.setText("Mettre à jour");
        btnModifModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifModifActionPerformed(evt);
            }
        });
        jPanel1.add(btnModifModif);
        btnModifModif.setBounds(210, 410, 140, 40);
        jPanel1.add(txtModifProduitID);
        txtModifProduitID.setBounds(170, 70, 217, 32);

        jLabel11.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 70, 129, 34);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifModifActionPerformed

            try {
                //String b = txtModifProduitID.getText();
                if (JOptionPane.showConfirmDialog(null, "modification sur le produit: "+selected , "modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                stm.executeUpdate("UPDATE produit SET designation='" + txtModifProduitDesignation.getText() + "',qte_actuel='" + txtModifProduitqteactu.getText()
                    + "',qte_alert='" + txtModifProduitqtealert.getText() + "',unite='" + comboModifunitemesure.getSelectedItem().toString()
                    + "',prixunit='" + parseFloat(txtModifProduitprixUnitaire.getText())+ "',categori='" + comboModifCategori.getSelectedItem()
                    + "' WHERE id='" + selected+"'");
                
                
                float prixUnitaire = parseFloat(txtModifProduitprixUnitaire.getText());

                stm.executeUpdate("UPDATE entre SET designation_produit='" + txtModifProduitDesignation.getText() + "',unite='" + comboModifunitemesure.getSelectedItem().toString()
                    + "',prixTotal='" + prixUnitaire+ "' * qte_recu WHERE id_produit='" +selected+"' && etat = 'ouvert'");
                
                
                
                stm.executeUpdate("UPDATE entre SET designation_produit='" + txtModifProduitDesignation.getText() + "',unite='" + comboModifunitemesure.getSelectedItem().toString()
                    + "' WHERE id_produit='"+selected+"' && etat = 'ferme'");
                
                stm.executeUpdate("UPDATE sortie SET designation ='" + txtModifProduitDesignation.getText() + "',unite='" + comboModifunitemesure.getSelectedItem().toString()
                    + "' WHERE id_produit='" +selected+"'");
                
                stm.executeUpdate("UPDATE produit_fourni SET designation ='" + txtModifProduitDesignation.getText()
                    + "' WHERE id_produit='" +selected+"'");
                
                this.dispose();
                JOptionPane.showMessageDialog(null, "Succès!");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de modification !" + e.getMessage());
            System.err.println(e);
        }
        
        
        

    }//GEN-LAST:event_btnModifModifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifModif;
    private javax.swing.JComboBox comboModifCategori;
    private javax.swing.JComboBox comboModifunitemesure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtAjoutProduitimage;
    private javax.swing.JTextField txtModifProduitDesignation;
    private javax.swing.JTextField txtModifProduitID;
    private javax.swing.JTextField txtModifProduitprixUnitaire;
    private javax.swing.JTextField txtModifProduitqteactu;
    private javax.swing.JTextField txtModifProduitqtealert;
    // End of variables declaration//GEN-END:variables
}
