/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rango
 */
public class ReservationAdd extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm,stm1,stm4,stm5;
    ResultSet Rs;
    
    DefaultTableModel model_dispo = new DefaultTableModel();
    
    public ReservationAdd() {
        initComponents();
        
        comClient.setEnabled(false);
        btnReserver.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAffiche = new javax.swing.JButton();
        comNbr = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtdebut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfin = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        comClient = new javax.swing.JComboBox();
        btnReserver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tableDispo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(742, 480));
        setMinimumSize(new java.awt.Dimension(742, 480));
        setPreferredSize(new java.awt.Dimension(742, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        btnAffiche.setText("Afficher les tables disponibles");
        btnAffiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficheActionPerformed(evt);
            }
        });
        jPanel1.add(btnAffiche);
        btnAffiche.setBounds(247, 145, 261, 42);

        comNbr.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        comNbr.setForeground(new java.awt.Color(0, 153, 153));
        comNbr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous", "2", "4", "6", "8", "10" }));
        jPanel1.add(comNbr);
        comNbr.setBounds(376, 86, 132, 33);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de place:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(247, 86, 119, 33);

        txtdebut.setBackground(new java.awt.Color(0, 102, 102));
        txtdebut.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtdebut);
        txtdebut.setBounds(307, 46, 70, 29);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Début:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(247, 46, 50, 29);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fin:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(397, 46, 42, 29);

        txtfin.setBackground(new java.awt.Color(0, 102, 102));
        txtfin.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtfin);
        txtfin.setBounds(438, 46, 70, 29);

        txtdate.setBackground(new java.awt.Color(0, 102, 102));
        txtdate.setForeground(new java.awt.Color(0, 153, 153));
        txtdate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txtdate);
        txtdate.setBounds(308, 11, 200, 29);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(247, 11, 51, 29);

        comClient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Client 01", "Client 02", "Client 03", "Client 04" }));
        jPanel1.add(comClient);
        comClient.setBounds(10, 410, 220, 35);

        btnReserver.setText("Réserver la table");
        btnReserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserverActionPerformed(evt);
            }
        });
        jPanel1.add(btnReserver);
        btnReserver.setBounds(550, 410, 180, 35);

        tbl_tableDispo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Designation", "Nombre de place"
            }
        ));
        tbl_tableDispo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tableDispoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tableDispo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 195, 720, 200);

        jLabel5.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ajout");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 160, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-120, 10, 242, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("ex: 01:00:00");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(520, 50, 90, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficheActionPerformed
        afficher_dispo();
    }//GEN-LAST:event_btnAfficheActionPerformed

    private void tbl_tableDispoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tableDispoMouseClicked
        comClient.setEnabled(true);
        btnReserver.setEnabled(true);
    }//GEN-LAST:event_tbl_tableDispoMouseClicked

    private void btnReserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserverActionPerformed
        String date = String.format("%1$tY-%1$tm-%1$td",txtdate.getDate());
        String debut = txtdebut.getText();
        String fin = txtfin.getText();
        int val = tbl_tableDispo.getSelectedRow();
        
        String id_table = tbl_tableDispo.getValueAt(val, 0).toString();
        String table = tbl_tableDispo.getValueAt(val, 1).toString();
        String client = comClient.getSelectedItem().toString();
        

        String requete = "insert into reservation(des_table,nom_client,date,heur_debut,heur_fin,etat,id_table)VALUES('"
        + table + "','" + client + "','" + date
        + "','" + debut + "','"+fin+"','En attente','"+id_table+"')";
        
        try {
                        stm.executeUpdate(requete);
                        JOptionPane.showMessageDialog(null, "Réservation au nom de: "+client+" ajouté");

                         this.setVisible(false);
                         
                    } catch (HeadlessException | SQLException ex)   {
                        JOptionPane.showMessageDialog(null, "erreur 1");
                    }
    }//GEN-LAST:event_btnReserverActionPerformed
private void afficher_dispo() {
if (txtdate.getDate() == null || txtdebut.getText().equals("") || txtfin.getText().equals("")){
    
    JOptionPane.showMessageDialog(null, "Completez tous les champs necessaires!");
    
}else{
    
    
    
    
if (comNbr.getSelectedItem().toString().equals("Tous")){
    model_dispo.setColumnCount(0);
        model_dispo.addColumn("ID");
        model_dispo.addColumn("Designation");
        model_dispo.addColumn("Nombre de place");
       
        comClient.setEnabled(false);
        btnReserver.setEnabled(false);
      
        String date = String.format("%1$tY-%1$tm-%1$td",txtdate.getDate());
     
        model_dispo.setRowCount(0);
        try {
                //model_dispo.setRowCount(0);
                stm1 = conn.obtenirconnexion().createStatement();
                ResultSet fr1 = stm1.executeQuery("Select * from table1");
                    
                while (fr1.next())   {
                        
                             
                        try {
                            //model_dispo.setRowCount(0);
                            stm = conn.obtenirconnexion().createStatement();
                            ResultSet fr = stm.executeQuery("Select * from reservation where des_table = '"
                            +fr1.getString("designation_table")+"' && date = '"+date+"' && (heur_debut between '"+txtdebut.getText()+"' and '"+txtfin.getText()+"' || heur_fin between '"+txtdebut.getText()+"' and '"+txtfin.getText()+"' )");
                                if (fr.next())   {
                                    if(fr.getTime(5).toString().equals(txtfin.getText()) || fr.getTime(6).toString().equals(txtdebut.getText()) ){
                                        
                                        model_dispo.addRow(new Object[]{fr1.getString("id_table"),fr1.getString("designation_table"),
                                            fr1.getString("nbr_place")});
                                        
                                    }else{
                                        
                                    }

                                                  }else{
                                    model_dispo.addRow(new Object[]{fr1.getString("id_table"),fr1.getString("designation_table"),
                                            fr1.getString("nbr_place")});
                                }
 
                        } catch (SQLException e) {System.err.println(e);}

                                        }
                    tbl_tableDispo.setModel(model_dispo);
            } catch (SQLException e) {System.err.println(e);}
    
    
    
}else{
        model_dispo.setColumnCount(0);
        model_dispo.addColumn("ID");
        model_dispo.addColumn("Designation");
        model_dispo.addColumn("Nombre de place");
        
        
        comClient.setEnabled(false);
        btnReserver.setEnabled(false);
        
       
        String date = String.format("%1$tY-%1$tm-%1$td",txtdate.getDate());
   
        String nbrPlace = comNbr.getSelectedItem().toString();
        
        model_dispo.setRowCount(0);
        try {
                //model_dispo.setRowCount(0);
                stm1 = conn.obtenirconnexion().createStatement();
                ResultSet fr1 = stm1.executeQuery("Select * from table1 where nbr_place = '"+nbrPlace+"'");
                    
                while (fr1.next())   {
                        
                             
                        try {
                            //model_dispo.setRowCount(0);
                            stm = conn.obtenirconnexion().createStatement();
                            ResultSet fr = stm.executeQuery("Select * from reservation where des_table = '"
                            +fr1.getString("designation_table")+"' && date = '"+date+"' && (heur_debut between '"+txtdebut.getText()+"' and '"+txtfin.getText()+"' || heur_fin between '"+txtdebut.getText()+"' and '"+txtfin.getText()+"' )");
                                if (fr.next())   {
                                     if(fr.getTime(5).toString().equals(txtfin.getText()) || fr.getTime(6).toString().equals(txtdebut.getText()) ){
                                        
                                        model_dispo.addRow(new Object[]{fr1.getString("id_table"),fr1.getString("designation_table"),
                                            fr1.getString("nbr_place")});
                                        
                                    }else{
                                        
                                    }

                                                  }else{
                                    model_dispo.addRow(new Object[]{fr1.getString("id_table"),fr1.getString("designation_table"),
                                            fr1.getString("nbr_place")});
                                }
 
                        } catch (SQLException e) {System.err.println(e);}

                                        }
                    tbl_tableDispo.setModel(model_dispo);
            } catch (SQLException e) {System.err.println(e);}
}
}
}
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAffiche;
    private javax.swing.JButton btnReserver;
    private javax.swing.JComboBox comClient;
    private javax.swing.JComboBox comNbr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_tableDispo;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtdebut;
    private javax.swing.JTextField txtfin;
    // End of variables declaration//GEN-END:variables
}
