/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rango
 */
public class Table extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm,stm1;
    ResultSet Rs;
    
    public String selected_table;
    public int indic = 0;
    
    DefaultTableModel model_table = new DefaultTableModel();
    
    public Table() {
        initComponents();
        
        
        afficher_table();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_table = new javax.swing.JTable();
        btnTableSuppr = new javax.swing.JButton();
        btnTableModif = new javax.swing.JButton();
        btnTableAjout = new javax.swing.JButton();
        txtTableTotal = new javax.swing.JLabel();
        txtTableActive = new javax.swing.JLabel();
        txtTableInactive = new javax.swing.JLabel();
        btn_menuPrincial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(803, 501));
        setMinimumSize(new java.awt.Dimension(803, 501));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tables");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 70, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-120, 10, 242, 40);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TOTAL");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Active(s):");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("En maintenance:");

        tbl_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Designation", "Nombre de place ", "Etat"
            }
        ));
        tbl_table.setRowHeight(30);
        tbl_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_table);

        btnTableSuppr.setText("Supprimer");
        btnTableSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableSupprActionPerformed(evt);
            }
        });

        btnTableModif.setText("Modifier");
        btnTableModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableModifActionPerformed(evt);
            }
        });

        btnTableAjout.setText("Ajouter");
        btnTableAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableAjoutActionPerformed(evt);
            }
        });

        txtTableTotal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtTableTotal.setForeground(new java.awt.Color(0, 204, 255));
        txtTableTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txtTableActive.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtTableActive.setForeground(new java.awt.Color(0, 204, 255));
        txtTableActive.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txtTableInactive.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtTableInactive.setForeground(new java.awt.Color(0, 204, 255));
        txtTableInactive.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_menuPrincial.setBackground(java.awt.Color.black);
        btn_menuPrincial.setForeground(new java.awt.Color(255, 255, 255));
        btn_menuPrincial.setText("Menus principal");
        btn_menuPrincial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuPrincialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTableTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTableActive, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTableInactive, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTableAjout, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addGap(411, 411, 411)
                        .addComponent(btnTableModif, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTableSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_menuPrincial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btn_menuPrincial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTableAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTableModif, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTableSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTableInactive, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTableActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTableTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, txtTableActive, txtTableInactive, txtTableTotal});

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void afficher_table() {
        model_table.setColumnCount(0);
        model_table.addColumn("ID");
        model_table.addColumn("Designation");
        model_table.addColumn("Nombre de place");
        model_table.addColumn("Etat");
        
        btnTableModif.setEnabled(false);
        btnTableSuppr.setEnabled(false);
    
        try {
                model_table.setRowCount(0);
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select * from table1 order by id_table");
                    while (fr.next())   {
                        model_table.addRow(new Object[]{fr.getString("id_table"),fr.getString("designation_table"),
                            fr.getString("nbr_place"), fr.getString("etat")});
                                        }
            } catch (SQLException e) {System.err.println(e);}
        
        tbl_table.setModel(model_table);
        
        
        try {
                stm1 = conn.obtenirconnexion().createStatement();
                ResultSet fr2 = stm.executeQuery("Select count(*) from table1");
                fr2.next();
                txtTableTotal.setText(fr2.getString(1));
               
                                        
            } catch (SQLException e) {System.err.println(e);}
        
        try {
                stm1 = conn.obtenirconnexion().createStatement();
                ResultSet fr2 = stm.executeQuery("Select count(*) from table1 where etat='Active'");
                fr2.next();
                txtTableActive.setText(fr2.getString(1));
                
            } catch (SQLException e) {System.err.println(e);}
        
        
        try {
                stm1 = conn.obtenirconnexion().createStatement();
                ResultSet fr2 = stm.executeQuery("Select count(*) from table1 where etat='Inactive'");
                fr2.next();
                txtTableInactive.setText(fr2.getString(1));
                
            } catch (SQLException e) {System.err.println(e);}
        
 
}    
    
    
    private void btnTableAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableAjoutActionPerformed
        TableAjout a = new TableAjout();
        a.setVisible(true);
        
        
    }//GEN-LAST:event_btnTableAjoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       login.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnTableModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableModifActionPerformed
        int i = tbl_table.getSelectedRow();
        String id_men = tbl_table.getValueAt(i, 0).toString();
        
        try{
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select * from reservation where id_table ='"+id_men+"'");
                if(fr.next()){
                    JOptionPane.showMessageDialog(null, "Impossible de modifier,\nCette table est encore sous réservation!");
                
                }else{
                    TableModif a = new TableModif();
                    a.setVisible(true);
                }
                        

            }catch (HeadlessException | SQLException ex) {
            }
 
    }//GEN-LAST:event_btnTableModifActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        afficher_table();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tbl_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tableMouseClicked
        int select = tbl_table.getSelectedRow();
        selected_table = tbl_table.getValueAt(select, 0).toString();
        btnTableModif.setEnabled(true);
        btnTableSuppr.setEnabled(true);
    }//GEN-LAST:event_tbl_tableMouseClicked

    private void btnTableSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableSupprActionPerformed
        int i = tbl_table.getSelectedRow();
        String id = tbl_table.getValueAt(i, 0).toString();
        if(id.length() == 0){JOptionPane.showMessageDialog(null, "veuillez séléctionner la table à supprimer");}else {
            try {
                if (JOptionPane.showConfirmDialog(null, "voulez-vous vraiment supprimer: "+id+" ?" , "supprimer une table",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                if (id.length() != 0) {

                    stm.executeUpdate("Delete From table1 where id_table = '" + id+"'");
                    JOptionPane.showMessageDialog(null, "\""+id +"\" supprimé de la liste!");
                    
                    
                    indic = 1;
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Veuillez remplire le champ Numero");
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de suppression \n" + e.getMessage());
        }
        }
    }//GEN-LAST:event_btnTableSupprActionPerformed

    private void btn_menuPrincialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuPrincialActionPerformed
        login.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menuPrincialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTableAjout;
    private javax.swing.JButton btnTableModif;
    private javax.swing.JButton btnTableSuppr;
    private javax.swing.JButton btn_menuPrincial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_table;
    private javax.swing.JLabel txtTableActive;
    private javax.swing.JLabel txtTableInactive;
    private javax.swing.JLabel txtTableTotal;
    // End of variables declaration//GEN-END:variables
}
