/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.Color;
import java.awt.HeadlessException;
import static java.lang.Float.parseFloat;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rango
 */
public class TableModif extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm;
    ResultSet Rs;
    String id_table = MenuPrincipal.tables.selected_table;
    public TableModif() {
        initComponents();
        
        
        txtTableModifID.setText(id_table);
        txtTableModifID.setEditable(false);
       
        try{
                stm = conn.obtenirconnexion().createStatement();
                //String des = txtModifProduitDesignation.getText();
                ResultSet fr = stm.executeQuery("Select * from table1 where id_table ='"+id_table+"'");

                fr.next();

                        txtTableModifDesignation.setText(fr.getString(3));
                        txtTableModifNbrPlace.setText(fr.getString(4));
                        comTableModifEtat.setSelectedItem(fr.getString(5));

                //}else { }

                
            }catch (HeadlessException | SQLException ex) {
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTableModifID = new javax.swing.JTextField();
        txtTableModifDesignation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTableModifNbrPlace = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comTableModifEtat = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(418, 392));
        setMinimumSize(new java.awt.Dimension(418, 392));
        setPreferredSize(new java.awt.Dimension(418, 392));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(36, 106, 133, 33);
        getContentPane().add(txtTableModifID);
        txtTableModifID.setBounds(179, 106, 194, 33);
        getContentPane().add(txtTableModifDesignation);
        txtTableModifDesignation.setBounds(179, 145, 194, 33);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Designation:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(36, 145, 133, 33);
        getContentPane().add(txtTableModifNbrPlace);
        txtTableModifNbrPlace.setBounds(179, 184, 194, 33);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de place:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 184, 133, 33);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Etat:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(36, 223, 133, 33);

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(228, 305, 106, 43);

        comTableModifEtat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive" }));
        getContentPane().add(comTableModifEtat);
        comTableModifEtat.setBounds(179, 223, 194, 33);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modification");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 130, 40);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-70, 10, 250, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
                //String b = txtModifProduitID.getText();
                if (JOptionPane.showConfirmDialog(null, "modification sur la table: "+id_table , "modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                stm.executeUpdate("UPDATE table1 SET designation_table='" + txtTableModifDesignation.getText() + "',nbr_place='" + txtTableModifNbrPlace.getText()
                    + "',etat='" + comTableModifEtat.getSelectedItem().toString()
                    + "' WHERE id_table='" + id_table+"'");
                JOptionPane.showMessageDialog(null, "Succès!");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de modification !" + e.getMessage());
            System.err.println(e);
        }
        
        this.dispose();
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableModif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comTableModifEtat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTableModifDesignation;
    private javax.swing.JTextField txtTableModifID;
    private javax.swing.JTextField txtTableModifNbrPlace;
    // End of variables declaration//GEN-END:variables
}
