/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockcarre;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rango
 */
public class User extends javax.swing.JFrame {

    conect conn = new conect();
    Statement stm,stm1;
    ResultSet Rs;
    
    public String selected_user;
    
    DefaultTableModel model_user = new DefaultTableModel();
    
    public User() {
        initComponents();
        
        afficher_user();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnUserAdd = new javax.swing.JButton();
        btnUserModif = new javax.swing.JButton();
        btnUserSuppr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable();
        btn_menuPrincial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(554, 472));
        setMinimumSize(new java.awt.Dimension(554, 472));
        setPreferredSize(new java.awt.Dimension(554, 472));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Utilisateur");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 120, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockcarre/t.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-90, 10, 242, 40);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnUserAdd.setText("Ajouter");
        btnUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAddActionPerformed(evt);
            }
        });

        btnUserModif.setText("Modifier");
        btnUserModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserModifActionPerformed(evt);
            }
        });

        btnUserSuppr.setText("Supprimer");
        btnUserSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSupprActionPerformed(evt);
            }
        });

        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Table", "Client", "Téléphone", "Date", "Debut", "Fin", "Etat"
            }
        ));
        tbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_user);

        btn_menuPrincial.setBackground(java.awt.Color.black);
        btn_menuPrincial.setForeground(new java.awt.Color(255, 255, 255));
        btn_menuPrincial.setText("Menus principal");
        btn_menuPrincial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuPrincialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_menuPrincial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUserModif, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnUserSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_menuPrincial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserModif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void afficher_user() {
        model_user.setColumnCount(0);
        model_user.addColumn("ID");
        model_user.addColumn("Mot de pass");
        model_user.addColumn("Catégorie");
        
        
        
        btnUserModif.setEnabled(false);
        btnUserSuppr.setEnabled(false);
    
        try {
                model_user.setRowCount(0);
                stm = conn.obtenirconnexion().createStatement();
                ResultSet fr = stm.executeQuery("Select * from user order by id");
                    while (fr.next())   {
                        model_user.addRow(new Object[]{fr.getString("id"),fr.getString("mdp"),
                            fr.getString("type")});
                                        }
            } catch (SQLException e) {System.err.println(e);}
        
        tbl_user.setModel(model_user);
        
        
//        try {
//                stm1 = conn.obtenirconnexion().createStatement();
//                ResultSet fr2 = stm.executeQuery("Select count(*) from client");
//                fr2.next();
//                txtClientTotal.setText(fr2.getString(1));
//               
//                                        
//            } catch (SQLException e) {System.err.println(e);}
    
    
    
}  
    
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        login.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAddActionPerformed
       UserAdd user = new UserAdd();
       user.setVisible(true);
    }//GEN-LAST:event_btnUserAddActionPerformed

    private void btnUserModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserModifActionPerformed
        UserModif user2 = new UserModif();
       user2.setVisible(true);
       
    }//GEN-LAST:event_btnUserModifActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        afficher_user();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tbl_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_userMouseClicked
        int val = tbl_user.getSelectedRow();
        selected_user = tbl_user.getValueAt(val, 0).toString();
         btnUserModif.setEnabled(true);
        btnUserSuppr.setEnabled(true);
        
    }//GEN-LAST:event_tbl_userMouseClicked

    private void btnUserSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSupprActionPerformed
        int i = tbl_user.getSelectedRow();
        String id = tbl_user.getValueAt(i, 0).toString();
        
            try {
                if (JOptionPane.showConfirmDialog(null, "voulez-vous vraiment supprimer: "+id+" ?" , "supprimer l'utilisateur",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                if (id.length() != 0) {
                    stm.executeUpdate("Delete From user where id = '" + id+"'");
                    JOptionPane.showMessageDialog(null, "\""+id +"\" supprimé de la liste!");
                    //afficher_table();
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Veuillez remplire le champ Numero");
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de suppression \n" + e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_btnUserSupprActionPerformed

    private void btn_menuPrincialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuPrincialActionPerformed
        login.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menuPrincialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserAdd;
    private javax.swing.JButton btnUserModif;
    private javax.swing.JButton btnUserSuppr;
    private javax.swing.JButton btn_menuPrincial;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_user;
    // End of variables declaration//GEN-END:variables
}
